# Generated by Django 3.1.6 on 2021-02-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildyourpc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='frequency',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='memoryram',
            name='frequency',
            field=models.FloatField(),
        ),
    ]
