# Generated by Django 3.1.6 on 2021-02-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildyourpc', '0002_auto_20210222_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='ram_quantity',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='computer',
            name='storage_quantity',
            field=models.JSONField(default=dict),
        ),
    ]
